package main;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import com.github.javaparser.utils.SourceRoot;
import java.nio.file.Paths;
import graph.CodeBlockNode;
import parser.StatementVisitor;

public class Main {
    public static void main(String[] args) {
        try {
            String className = "SourceCode";
            String fileName = "SourceCode.java";
            String functionName = "checkMultiples";

            // Set up a combined type solver (this is used for symbol resolution in the JavaParser library)
            String sourcePath = "src/main/java/source";
            CombinedTypeSolver combinedSolver = new CombinedTypeSolver(
                    new ReflectionTypeSolver(),
                    new JavaParserTypeSolver(Paths.get(sourcePath))
            );

            // Set up a parser configuration with the combined type solver
            ParserConfiguration parserConfiguration = new ParserConfiguration()
                    .setSymbolResolver(new JavaSymbolSolver(combinedSolver));

            // Parse the source code
            SourceRoot sr = new SourceRoot(Paths.get(sourcePath), parserConfiguration);
            //CompilationUnit: a top-level representation of a parsed Java source file, encapsulating all its elements including package declaration, imports, types, classes, and interfaces.
            CompilationUnit cu = sr.parse("", fileName);


            // Analyze the source code
            cu.getClassByName(className).ifPresent(classDeclaration -> {
                // Get the method (checkMultiples in this case) and analyze it
                MethodDeclaration method = classDeclaration.getMethodsByName(functionName).get(0);

                //Root graph node
                CodeBlockNode root = new CodeBlockNode();
                // Create a graph by visiting AST generated by sr.parse
                StatementVisitor statementVisitor = new StatementVisitor();
                statementVisitor.visit(method, root);

                // Visualize the control flow graph?
                root.visualizer(0);
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}